package common

import org.apache.spark.sql.types.{DataTypes, StructType,StructField}

object Schemas {
  val partyidschema = new StructType()
    .add("MDM_ID", DataTypes.StringType)
    .add("PRTY_ASSC_TYP_CD", DataTypes.StringType)
    .add("PRTY_ASSC_VL", DataTypes.StringType)
    .add("PRTY_ASSC_STTS_CD",DataTypes.StringType)
    .add("PRTY_ASSC_VL_TYP_CD",DataTypes.StringType)
    .add("LAST_UPDATE_DATE",DataTypes.TimestampType)

  val opportunitylineitemschema = new StructType()
    .add("Id",  DataTypes.StringType)
    .add("OpportunityId",  DataTypes.StringType)
    .add("SortOrder",  DataTypes.StringType)
    .add("PricebookEntryId",  DataTypes.StringType)
    .add("Product2Id",  DataTypes.StringType)
    .add("ProductCode",  DataTypes.StringType)
    .add("Name",  DataTypes.StringType)
    .add("CurrencyIsoCode",  DataTypes.StringType)
    .add("Quantity",  DataTypes.StringType)
    .add("Discount",  DataTypes.StringType)
    .add("Subtotal",  DataTypes.StringType)
    .add("TotalPrice",  DataTypes.StringType)
    .add("UnitPrice",  DataTypes.StringType)
    .add("ListPrice",  DataTypes.StringType)
    .add("ServiceDate",  DataTypes.StringType)
    .add("HasRevenueSchedule",  DataTypes.StringType)
    .add("HasQuantitySchedule",  DataTypes.StringType)
    .add("Description",  DataTypes.StringType)
    .add("HasSchedule",  DataTypes.StringType)
    .add("CanUseQuantitySchedule",  DataTypes.StringType)
    .add("CanUseRevenueSchedule",  DataTypes.StringType)
    .add("CreatedDate",  DataTypes.StringType)
    .add("CreatedById",  DataTypes.StringType)
    .add("LastModifiedDate",  DataTypes.StringType)
    .add("LastModifiedById",  DataTypes.StringType)
    .add("SystemModstamp",  DataTypes.StringType)
    .add("IsDeleted",  DataTypes.StringType)
    .add("Business_Group__c",  DataTypes.StringType)
    .add("GBU__c",  DataTypes.StringType)
    .add("Legacy_Ref_Id__c",  DataTypes.StringType)
    .add("OpportunityID__c",  DataTypes.StringType)
    .add("OpportunityStage__c",  DataTypes.StringType)
    .add("Opportunity_Close_Date__c",  DataTypes.StringType)
    .add("ProductId__c",  DataTypes.StringType)
    .add("Product__c",  DataTypes.StringType)
    .add("Attach__c",  DataTypes.StringType)
    .add("Contract__c",  DataTypes.StringType)
    .add("End_Date__c",  DataTypes.StringType)
    .add("First_12_Month_Value__c",  DataTypes.StringType)
    .add("First_Fiscal_Year_Value__c",  DataTypes.StringType)
    .add("Margin_Amount__c",  DataTypes.StringType)
    .add("Margin_Percentage__c",  DataTypes.StringType)
    .add("Sales_Doc_Nbr__c",  DataTypes.StringType)
    .add("Start_Date__c",  DataTypes.StringType)
    .add("Contract_End_Date__c",  DataTypes.StringType)
    .add("Contract_Start_Date__c",  DataTypes.StringType)
    .add("Error_Stage_Sub_Total__c",  DataTypes.StringType)
    .add("HP_Not_Pursued_Stage_Count__c",  DataTypes.StringType)
    .add("HP_Not_Pursued_Stage_Sub_Total__c",  DataTypes.StringType)
    .add("HasProductLine__c",  DataTypes.StringType)
    .add("HasSubProductLine__c",  DataTypes.StringType)
    .add("Keep__c",  DataTypes.StringType)
    .add("Lost_Or_HP_Not_Pursed_Not_123_Count__c",  DataTypes.StringType)
    .add("Lost_Or_HP_Not_Pursed_Not_123_Sub_Total__c",  DataTypes.StringType)
    .add("Lost_Stage_Count__c",  DataTypes.StringType)
    .add("Lost_Stage_Sub_Total__c",  DataTypes.StringType)
    .add("Mix_Flag__c",  DataTypes.StringType)
    .add("Month_1_Revenue__c",  DataTypes.StringType)
    .add("Month_2_Revenue__c",  DataTypes.StringType)
    .add("Month_3_Revenue__c",  DataTypes.StringType)
    .add("Month_4_Revenue__c",  DataTypes.StringType)
    .add("Month_5_Revenue__c",  DataTypes.StringType)
    .add("ProductName__c",  DataTypes.StringType)
    .add("Product_Line__c",  DataTypes.StringType)
    .add("Program_Code__c",  DataTypes.StringType)
    .add("Program__c",  DataTypes.StringType)
    .add("Quote_Number__c",  DataTypes.StringType)
    .add("RTS_Component__c",  DataTypes.StringType)
    .add("RTS__c",  DataTypes.StringType)
    .add("Status__c",  DataTypes.StringType)
    .add("Sub_Product_Line__c",  DataTypes.StringType)
    .add("Total_Incremental_Revenue__c",  DataTypes.StringType)
    .add("Win_Back__c",  DataTypes.StringType)
    .add("X06_Stage_Count__c",  DataTypes.StringType)
    .add("X06_Stage_Sub_Total__c",  DataTypes.StringType)
    .add("FFYR_Margin_Amount__c",  DataTypes.StringType)
    .add("BigMachines__Origin_Quote__c",  DataTypes.StringType)
    .add("BigMachines__Synchronization_Id__c",  DataTypes.StringType)
    .add("Add_days_to_BookShip_Date__c",  DataTypes.StringType)
    .add("Month_10_Revenue__c",  DataTypes.StringType)
    .add("Month_11_Revenue__c",  DataTypes.StringType)
    .add("Month_12_Revenue__c",  DataTypes.StringType)
    .add("Month_6_Revenue__c",  DataTypes.StringType)
    .add("Month_7_Revenue__c",  DataTypes.StringType)
    .add("Month_8_Revenue__c",  DataTypes.StringType)
    .add("Month_9_Revenue__c",  DataTypes.StringType)
    .add("Summation_Product_Name__c",  DataTypes.StringType)
    .add("HP_Quote__c",  DataTypes.StringType)
    .add("ICOEM__c",  DataTypes.StringType)
    .add("Max_Book_Ship_date__c",  DataTypes.StringType)
    .add("Quote_End_Date__c",  DataTypes.StringType)
    .add("Quote_Start_Date__c",  DataTypes.StringType)
    .add("Sales_Motion__c",  DataTypes.StringType)
    .add("Scope_Type__c",  DataTypes.StringType)
    .add("Category__c",  DataTypes.StringType)
    .add("FCST_Product_Specialty_Key_List__c",  DataTypes.StringType)
    .add("UnitPriceForResubmit__c",  DataTypes.StringType)
    .add("isInsertedOLI__c",  DataTypes.StringType)
    .add("isUpdatedOLI__c",  DataTypes.StringType)
    .add("pse__Added_To_Project__c",  DataTypes.StringType)
    .add("pse__IsServicesProductLine__c",  DataTypes.StringType)
    .add("Fiscal_Quarter__c",  DataTypes.StringType)
    .add("f1__c",  DataTypes.StringType)
    .add("f2__c",  DataTypes.StringType)
    .add("f3__c",  DataTypes.StringType)
    .add("f4__c",  DataTypes.StringType)
    .add("Product_Code__c",  DataTypes.StringType)
    .add("Tier_1_Sub_Total__c",  DataTypes.StringType)
    .add("Tier_1_Unit_Price__c",  DataTypes.StringType)
    .add("Product_Service__c",  DataTypes.StringType)
    .add("Product_Group__c",  DataTypes.StringType)
    .add("From_Lead_Merge__c",  DataTypes.StringType)
    .add("Sub_Product_Id__c",  DataTypes.StringType)
    .add("IsActive__c",  DataTypes.StringType)
    .add("Oppty_Product_Safe_ID__c",  DataTypes.StringType)

  val stidaccountsschema = new StructType()
    .add("Id",  DataTypes.StringType)
    .add("OwnerId",  DataTypes.StringType)
    .add("IsDeleted",  DataTypes.StringType)
    .add("Name",  DataTypes.StringType)
    .add("CurrencyIsoCode",  DataTypes.StringType)
    .add("CreatedDate",  DataTypes.StringType)
    .add("CreatedById",  DataTypes.StringType)
    .add("LastModifiedDate",  DataTypes.StringType)
    .add("LastModifiedById",  DataTypes.StringType)
    .add("SystemModstamp",  DataTypes.StringType)
    .add("Account_To_Territory_Id__c",  DataTypes.StringType)
    .add("Account__c",  DataTypes.StringType)
    .add("Assigned_On__c",  DataTypes.StringType)
    .add("Assignment_Type__c",  DataTypes.StringType)
    .add("Sales_Territory_Definition__c",  DataTypes.StringType)
    .add("Sales_Territory__c",  DataTypes.StringType)
    .add("AddToAccountProcess__c",  DataTypes.StringType)
    .add("TrackAssociationToDelete__c",  DataTypes.StringType)
    .add("Crediting_Type__c",  DataTypes.StringType)
    .add("MyComp_ID__c",  DataTypes.StringType)
    .add("Sales_Territory_Type__c",  DataTypes.StringType)
    .add("Territory_Country__c",  DataTypes.StringType)
    .add("Territory_Region__c",  DataTypes.StringType)
    .add("MDCP_Site_Instance_ID__c",  DataTypes.StringType)
    .add("STAACustomerSOMFlag__c",  DataTypes.StringType)
    .add("Business_Unit__c",  DataTypes.StringType)
    .add("Sales_Lobby_Link__c",  DataTypes.StringType)

  val accountsschema = StructType(
    List(
      StructField("Id",DataTypes.StringType),
      StructField("IsDeleted",DataTypes.StringType),
      StructField("MasterRecordId",DataTypes.StringType),
      StructField("Name",DataTypes.StringType),
      StructField("LastName",DataTypes.StringType),
      StructField("FirstName",DataTypes.StringType),
      StructField("Salutation",DataTypes.StringType),
      StructField("Type",DataTypes.StringType),
      StructField("RecordTypeId",DataTypes.StringType),
      StructField("ParentId",DataTypes.StringType),
      StructField("BillingStreet",DataTypes.StringType),
      StructField("BillingCity",DataTypes.StringType),
      StructField("BillingState",DataTypes.StringType),
      StructField("BillingPostalCode",DataTypes.StringType),
      StructField("BillingCountry",DataTypes.StringType),
      StructField("BillingLatitude",DataTypes.StringType),
      StructField("BillingLongitude",DataTypes.StringType),
      StructField("BillingGeocodeAccuracy",DataTypes.StringType),
      StructField("ShippingStreet",DataTypes.StringType),
      StructField("ShippingCity",DataTypes.StringType),
      StructField("ShippingState",DataTypes.StringType),
      StructField("ShippingPostalCode",DataTypes.StringType),
      StructField("ShippingCountry",DataTypes.StringType),
      StructField("ShippingLatitude",DataTypes.StringType),
      StructField("ShippingLongitude",DataTypes.StringType),
      StructField("ShippingGeocodeAccuracy",DataTypes.StringType),
      StructField("Phone",DataTypes.StringType),
      StructField("Fax",DataTypes.StringType),
      StructField("AccountNumber",DataTypes.StringType),
      StructField("Website",DataTypes.StringType),
      StructField("PhotoUrl",DataTypes.StringType),
      StructField("Sic",DataTypes.StringType),
      StructField("Industry",DataTypes.StringType),
      StructField("AnnualRevenue",DataTypes.StringType),
      StructField("NumberOfEmployees",DataTypes.StringType),
      StructField("Ownership",DataTypes.StringType),
      StructField("TickerSymbol",DataTypes.StringType),
      StructField("Description",DataTypes.StringType),
      StructField("Rating",DataTypes.StringType),
      StructField("Site",DataTypes.StringType),
      StructField("CurrencyIsoCode",DataTypes.StringType),
      StructField("OwnerId",DataTypes.StringType),
      StructField("CreatedDate",DataTypes.StringType),
      StructField("CreatedById",DataTypes.StringType),
      StructField("LastModifiedDate",DataTypes.StringType),
      StructField("LastModifiedById",DataTypes.StringType),
      StructField("SystemModstamp",DataTypes.StringType),
      StructField("LastActivityDate",DataTypes.StringType),
      StructField("LastViewedDate",DataTypes.StringType),
      StructField("LastReferencedDate",DataTypes.StringType),
      StructField("IsPartner",DataTypes.StringType),
      StructField("IsCustomerPortal",DataTypes.StringType),
      StructField("PersonContactId",DataTypes.StringType),
      StructField("IsPersonAccount",DataTypes.StringType),
      StructField("ChannelProgramName",DataTypes.StringType),
      StructField("ChannelProgramLevelName",DataTypes.StringType),
      StructField("PersonMailingStreet",DataTypes.StringType),
      StructField("PersonMailingCity",DataTypes.StringType),
      StructField("PersonMailingState",DataTypes.StringType),
      StructField("PersonMailingPostalCode",DataTypes.StringType),
      StructField("PersonMailingCountry",DataTypes.StringType),
      StructField("PersonMailingLatitude",DataTypes.StringType),
      StructField("PersonMailingLongitude",DataTypes.StringType),
      StructField("PersonMailingGeocodeAccuracy",DataTypes.StringType),
      StructField("PersonOtherStreet",DataTypes.StringType),
      StructField("PersonOtherCity",DataTypes.StringType),
      StructField("PersonOtherState",DataTypes.StringType),
      StructField("PersonOtherPostalCode",DataTypes.StringType),
      StructField("PersonOtherCountry",DataTypes.StringType),
      StructField("PersonOtherLatitude",DataTypes.StringType),
      StructField("PersonOtherLongitude",DataTypes.StringType),
      StructField("PersonOtherGeocodeAccuracy",DataTypes.StringType),
      StructField("PersonMobilePhone",DataTypes.StringType),
      StructField("PersonHomePhone",DataTypes.StringType),
      StructField("PersonOtherPhone",DataTypes.StringType),
      StructField("PersonAssistantPhone",DataTypes.StringType),
      StructField("PersonEmail",DataTypes.StringType),
      StructField("PersonTitle",DataTypes.StringType),
      StructField("PersonDepartment",DataTypes.StringType),
      StructField("PersonAssistantName",DataTypes.StringType),
      StructField("PersonLeadSource",DataTypes.StringType),
      StructField("PersonBirthdate",DataTypes.StringType),
      StructField("PersonHasOptedOutOfEmail",DataTypes.StringType),
      StructField("PersonHasOptedOutOfFax",DataTypes.StringType),
      StructField("PersonDoNotCall",DataTypes.StringType),
      StructField("PersonLastCURequestDate",DataTypes.StringType),
      StructField("PersonLastCUUpdateDate",DataTypes.StringType),
      StructField("PersonEmailBouncedReason",DataTypes.StringType),
      StructField("PersonEmailBouncedDate",DataTypes.StringType),
      StructField("Jigsaw",DataTypes.StringType),
      StructField("JigsawCompanyId",DataTypes.StringType),
      StructField("AccountSource",DataTypes.StringType),
      StructField("SicDesc",DataTypes.StringType),
      StructField("AMID_L2__c",DataTypes.StringType),
      StructField("Account_E_mail__c",DataTypes.StringType),
      StructField("Account_Phonetical_Name_Capture_Latin__c",DataTypes.StringType),
      StructField("Active_Flag__c",DataTypes.StringType),
      StructField("Alliance_Partner_Flag__c",DataTypes.StringType),
      StructField("Alliance_Role__c",DataTypes.StringType),
      StructField("Channel_Partner_Flag__c",DataTypes.StringType),
      StructField("Confidential_Account__c",DataTypes.StringType),
      StructField("DUNS__c",DataTypes.StringType),
      StructField("Domestic_Ultimate_Duns__c",DataTypes.StringType),
      StructField("Global_Ultimate_DUNS_Number__c",DataTypes.StringType),
      StructField("Location_ID__c",DataTypes.StringType),
      StructField("MDCP_Organization_ID__c",DataTypes.StringType),
      StructField("Parent_Partner_ID__c",DataTypes.StringType),
      StructField("Parent_Partner_Name__c",DataTypes.StringType),
      StructField("Partner_Status__c",DataTypes.StringType),
      StructField("Partner_Type__c",DataTypes.StringType),
      StructField("Regions__c",DataTypes.StringType),
      StructField("Source_System_Account_ID__c",DataTypes.StringType),
      StructField("Valid_Business_Group__c",DataTypes.StringType),
      StructField("Alternate_Name__c",DataTypes.StringType),
      StructField("Coverage_Segmentation__c",DataTypes.StringType),
      StructField("EvaluateTerritory__c",DataTypes.StringType),
      StructField("Industry_Segment__c",DataTypes.StringType),
      StructField("Industry_Vertical__c",DataTypes.StringType),
      StructField("LastAssignmentDate__c",DataTypes.StringType),
      StructField("Named_Account__c",DataTypes.StringType),
      StructField("Non_Standard_Account__c",DataTypes.StringType),
      StructField("Partner_Portal_Eligible__c",DataTypes.StringType),
      StructField("Partner_Queue_Name__c",DataTypes.StringType),
      StructField("RAD__c",DataTypes.StringType),
      StructField("Sales_Region__c",DataTypes.StringType),
      StructField("Strike_Count__c",DataTypes.StringType),
      StructField("OrganizationNonLatin_ExtendedName__c",DataTypes.StringType),
      StructField("Global_Account_Reporting_Name__c",DataTypes.StringType),
      StructField("Private_Flag_Status__c",DataTypes.StringType),
      StructField("Tax_Identifier__c",DataTypes.StringType),
      StructField("Trade_Style_Name_2__c",DataTypes.StringType),
      StructField("Trade_Style_Name_3__c",DataTypes.StringType),
      StructField("Trade_Style_Name_4__c",DataTypes.StringType),
      StructField("Trade_Style_Name_5__c",DataTypes.StringType),
      StructField("World_Region__c",DataTypes.StringType),
      StructField("AccountProfileEvaluated__c",DataTypes.StringType),
      StructField("Blacklist_Type__c",DataTypes.StringType),
      StructField("Country_Code__c",DataTypes.StringType),
      StructField("HP_Lead_Status__c",DataTypes.StringType),
      StructField("HP_SFDC_Access__c",DataTypes.StringType),
      StructField("LastAcountProfAssignmentDate__c",DataTypes.StringType),
      StructField("LastCoverageAssignmentDate__c",DataTypes.StringType),
      StructField("LastIndustryAssignmentDate__c",DataTypes.StringType),
      StructField("Verified_Account__c",DataTypes.StringType),
      StructField("WorldRegion_Hierarchy__c",DataTypes.StringType),
      StructField("WorldRegion_Region__c",DataTypes.StringType),
      StructField("WorldRegion_SubRegion1__c",DataTypes.StringType),
      StructField("WorldRegion_SubRegion2__c",DataTypes.StringType),
      StructField("WorldRegion_SubRegion3__c",DataTypes.StringType),
      StructField("World_Region1__c",DataTypes.StringType),
      StructField("BG_Target_Segments__c",DataTypes.StringType),
      StructField("Case_Safe_ID__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship__c",DataTypes.StringType),
      StructField("MDCP_Partner_Organization_ID__c",DataTypes.StringType),
      StructField("MDCP_Site_Instance_Id__c",DataTypes.StringType),
      StructField("MDCP_Subscribed_Flag__c",DataTypes.StringType),
      StructField("Mdcp_SiteId__c",DataTypes.StringType),
      StructField("BigMachines__Partner_Organization__c",DataTypes.StringType),
      StructField("Business_Area_Group__c",DataTypes.StringType),
      StructField("D_B_Out_of_business__c",DataTypes.StringType),
      StructField("FTP_Username_Password__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship_ID__c",DataTypes.StringType),
      StructField("MDCP_Last_Synced__c",DataTypes.StringType),
      StructField("Organization_DUNS_Number__c",DataTypes.StringType),
      StructField("Organization_Unit__c",DataTypes.StringType),
      StructField("Primary_Business_Relationship__c",DataTypes.StringType),
      StructField("RPL_Last_Synced__c",DataTypes.StringType),
      StructField("RPL_status__c",DataTypes.StringType),
      StructField("Record_Subtype__c",DataTypes.StringType),
      StructField("Support_Type__c",DataTypes.StringType),
      StructField("Userkey__c",DataTypes.StringType),
      StructField("Market_Insights__c",DataTypes.StringType),
      StructField("pse__Services_Billing_Time_Period_Type__c",DataTypes.StringType),
      StructField("CKSW__BillingAddressKey__c",DataTypes.StringType),
      StructField("CKSW__BillingRegion__c",DataTypes.StringType),
      StructField("CKSW__Billing_District__c",DataTypes.StringType),
      StructField("CKSW__Contract_Type__c",DataTypes.StringType),
      StructField("CKSW__Key__c",DataTypes.StringType),
      StructField("CKSW__ShippingAddressKey__c",DataTypes.StringType),
      StructField("CKSW__ShippingDistrict__c",DataTypes.StringType),
      StructField("CKSW__ShippingRegion__c",DataTypes.StringType),
      StructField("Account_Region__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship_AppliesTo_Cd__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship_BAG_ID__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship_PanHP_Flag__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship_Process_Usg__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship_Typ_Cd__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship_Unit__c",DataTypes.StringType),
      StructField("MDCP_Business_Relationship_Usg_Typ_Cd__c",DataTypes.StringType),
      StructField("Parent_Organization__c",DataTypes.StringType),
      StructField("CKSW__TaskExists__c",DataTypes.StringType),
      StructField("fferpcore__IsBillingAddressValidated__c",DataTypes.StringType),
      StructField("Services360_Opt_Out_Reason__c",DataTypes.StringType),
      StructField("Focus_Account__c",DataTypes.StringType),
      StructField("Global_Account__c",DataTypes.StringType),
      StructField("Top_Account__c",DataTypes.StringType),
      StructField("AccountRegion__c",DataTypes.StringType),
      StructField("Is_GSD_Account__c",DataTypes.StringType),
      StructField("pse__ERP_Worker_Correlation_Id__c",DataTypes.StringType),
      StructField("pse__Add_BEIs_To_Existing_Batches__c",DataTypes.StringType),
      StructField("Services360_Account__c",DataTypes.StringType),
      StructField("fferpcore__IsShippingAddressValidated__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedBillingCity__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedBillingCountry__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedBillingPostalCode__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedBillingState__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedBillingStreet__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedShippingCity__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedShippingCountry__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedShippingPostalCode__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedShippingState__c",DataTypes.StringType),
      StructField("fferpcore__ValidatedShippingStreet__c",DataTypes.StringType),
      StructField("A_STAA_MDCP_Alignment__c",DataTypes.StringType),
      StructField("Account_Hierarchy_fields_LastUpdateDate__c",DataTypes.StringType),
      StructField("Account_ST_ID__c",DataTypes.StringType),
      StructField("Account_ST_Name__c",DataTypes.StringType),
      StructField("Account_Sensitivity_Icon__c",DataTypes.StringType),
      StructField("Account_Sensitivity__c",DataTypes.StringType),
      StructField("Partial_Account_ST_ID__c",DataTypes.StringType),
      StructField("Partial_Account_ST_Name__c",DataTypes.StringType),
      StructField("Partial_Account_fields_LastUpdateDate__c",DataTypes.StringType),
      StructField("Top_Parent_ST_ID__c",DataTypes.StringType),
      StructField("Top_Parent_ST_Name__c",DataTypes.StringType),
      StructField("GSD_Account_Domain_Managed__c",DataTypes.StringType),
      StructField("Latin_Account_Name__c",DataTypes.StringType),
      StructField("Service_Delivery_Account_Type__c",DataTypes.StringType),
      StructField("Govt_LLC__c",DataTypes.StringType),
      StructField("Number_of_Accounts__c",DataTypes.StringType),
      StructField("Group_Parent_Identifier__c",DataTypes.StringType),
      StructField("Evaluate_Duplicate_Opportunity__c",DataTypes.StringType),
      StructField("fferpcore__ExemptionCertificate__c",DataTypes.StringType),
      StructField("fferpcore__OutputVatCode__c",DataTypes.StringType),
      StructField("Market_Segmentation__c",DataTypes.StringType),
      StructField("fferpcore__SalesTaxStatus__c",DataTypes.StringType),
      StructField("fferpcore__TaxCode1__c",DataTypes.StringType),
      StructField("fferpcore__TaxCode2__c",DataTypes.StringType),
      StructField("fferpcore__TaxCode3__c",DataTypes.StringType),
      StructField("fferpcore__TaxCountryCode__c",DataTypes.StringType),
      StructField("fferpcore__VatRegistrationNumber__c",DataTypes.StringType),
      StructField("fferpcore__VatStatus__c",DataTypes.StringType),
      StructField("LID__LinkedIn_Company_Id__c",DataTypes.StringType),
      StructField("Account_Extension__c",DataTypes.StringType),
      StructField("eCommerce_Customer__c",DataTypes.StringType),
      StructField("GSD_Global_Duns__c",DataTypes.StringType),
      StructField("ringdna100__Call_Attempts__c",DataTypes.StringType),
      StructField("ringdna100__Days_Since_Last_Attempt__c",DataTypes.StringType),
      StructField("ringdna100__Email_Attempts__c",DataTypes.StringType),
      StructField("ringdna100__First_Inbound_Call__c",DataTypes.StringType),
      StructField("ringdna100__First_Outbound_Call__c",DataTypes.StringType),
      StructField("ringdna100__Last_Email_Attempt__c",DataTypes.StringType),
      StructField("ringdna100__Last_Inbound_Call__c",DataTypes.StringType),
      StructField("ringdna100__Last_Outbound_Call__c",DataTypes.StringType),
      StructField("ringdna100__Response_Type__c",DataTypes.StringType),
      StructField("ringdna100__RingDNA_Context__c",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Call_Attempt_Days__c",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Call_Attempt_Minutes__c",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Email_Attempt_Days__c",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Email_Attempt_Minutes__c",DataTypes.StringType),
      StructField("ringdna100__Time_to_First_Dial_Minutes__c",DataTypes.StringType),
      StructField("ringdna100__Time_to_First_Response__c",DataTypes.StringType),
      StructField("Last_Won_Opportunity_Age_Years__c",DataTypes.StringType),
      StructField("Last_Closed_Won_Opportunity__c",DataTypes.StringType),
      StructField("First_Name_Local__pc",DataTypes.StringType),
      StructField("Last_Name_Local__pc",DataTypes.StringType),
      StructField("Left_Company__pc",DataTypes.StringType),
      StructField("Phonetic_First_Name__pc",DataTypes.StringType),
      StructField("Phonetic_Last_Name__pc",DataTypes.StringType),
      StructField("Preferred_Customer_Language__pc",DataTypes.StringType),
      StructField("Preferred_Method_of_Contact__pc",DataTypes.StringType),
      StructField("BU_Lead__pc",DataTypes.StringType),
      StructField("BU__pc",DataTypes.StringType),
      StructField("Business_Function__pc",DataTypes.StringType),
      StructField("CID_Person_ID__pc",DataTypes.StringType),
      StructField("Department__pc",DataTypes.StringType),
      StructField("Eloqua_BU__pc",DataTypes.StringType),
      StructField("Eloqua_Email__pc",DataTypes.StringType),
      StructField("Eloqua_Lead_Score__pc",DataTypes.StringType),
      StructField("Email_Opt_In_Change_Date__pc",DataTypes.StringType),
      StructField("Fax_Opt_in_Change_Date__pc",DataTypes.StringType),
      StructField("HP_Customer_Self_Reported__pc",DataTypes.StringType),
      StructField("Industry__pc",DataTypes.StringType),
      StructField("Isolation_Status_Date__pc",DataTypes.StringType),
      StructField("Isolation_Status__pc",DataTypes.StringType),
      StructField("Job_Responsibilities__pc",DataTypes.StringType),
      StructField("Job_Seniority__pc",DataTypes.StringType),
      StructField("Lead_Source_Most_Recent__pc",DataTypes.StringType),
      StructField("Lead_Source_Original1__pc",DataTypes.StringType),
      StructField("Lead_Source__pc",DataTypes.StringType),
      StructField("List_Code__pc",DataTypes.StringType),
      StructField("List_ID__pc",DataTypes.StringType),
      StructField("Mail_Opt_in_Change_Date__pc",DataTypes.StringType),
      StructField("MailingCity__pc",DataTypes.StringType),
      StructField("MailingCountry__pc",DataTypes.StringType),
      StructField("MailingPostalCode__pc",DataTypes.StringType),
      StructField("MailingState__pc",DataTypes.StringType),
      StructField("MailingStreet__pc",DataTypes.StringType),
      StructField("Mobile_Opt_In_Change_Date__pc",DataTypes.StringType),
      StructField("OtherCountry__pc",DataTypes.StringType),
      StructField("OtherPhone__pc",DataTypes.StringType),
      StructField("OtherPostalCode__pc",DataTypes.StringType),
      StructField("OtherState__pc",DataTypes.StringType),
      StructField("OtherStreet__pc",DataTypes.StringType),
      StructField("Phone_Opt_in_Change_Date__pc",DataTypes.StringType),
      StructField("Phone__pc",DataTypes.StringType),
      StructField("Preference__pc",DataTypes.StringType),
      StructField("Preferred_Subjects__pc",DataTypes.StringType),
      StructField("Product_ID__pc",DataTypes.StringType),
      StructField("Qualification_team_ID__pc",DataTypes.StringType),
      StructField("Qualification_team_name__pc",DataTypes.StringType),
      StructField("ReportsToId__pc",DataTypes.StringType),
      StructField("SourceSystemContactID__pc",DataTypes.StringType),
      StructField("Standardized_Title__pc",DataTypes.StringType),
      StructField("Sub_BU__pc",DataTypes.StringType),
      StructField("Tactic_Code__pc",DataTypes.StringType),
      StructField("Tactic_Name__pc",DataTypes.StringType),
      StructField("Key_Contact_to__pc",DataTypes.StringType),
      StructField("Suppress_Marketing__pc",DataTypes.StringType),
      StructField("Suppression_End_Date__pc",DataTypes.StringType),
      StructField("Suppression_Start_Date__pc",DataTypes.StringType),
      StructField("Job_Role__pc",DataTypes.StringType),
      StructField("Case_Safe_ID__pc",DataTypes.StringType),
      StructField("GETSAT_TOPIC__Author_URL__pc",DataTypes.StringType),
      StructField("GETSAT_TOPIC__of_Actions__pc",DataTypes.StringType),
      StructField("IsPortalEnabled__pc",DataTypes.StringType),
      StructField("User__pc",DataTypes.StringType),
      StructField("MVC__pc",DataTypes.StringType),
      StructField("Primary_Super_User__pc",DataTypes.StringType),
      StructField("Contact_External_Id__pc",DataTypes.StringType),
      StructField("Customer_Division__pc",DataTypes.StringType),
      StructField("DPlus_Company_Reference__pc",DataTypes.StringType),
      StructField("appirio_core__Last_Access_Date__pc",DataTypes.StringType),
      StructField("Mailing_Street_2__pc",DataTypes.StringType),
      StructField("appirio_core__Licensed_Features__pc",DataTypes.StringType),
      StructField("Work_Phone_Extension__pc",DataTypes.StringType),
      StructField("appirio_core__PIN__pc",DataTypes.StringType),
      StructField("pse__Action_Calculate_Utilization__pc",DataTypes.StringType),
      StructField("pse__Action_Update_Current_Time_Period__pc",DataTypes.StringType),
      StructField("pse__Actuals_Last_Update_Date__pc",DataTypes.StringType),
      StructField("pse__Actuals_Last_Updated_By__pc",DataTypes.StringType),
      StructField("pse__Allow_Timecards_Without_Assignment__pc",DataTypes.StringType),
      StructField("pse__Billable_External_Hours__pc",DataTypes.StringType),
      StructField("pse__Billable_Internal_Hours__pc",DataTypes.StringType),
      StructField("pse__Billed__pc",DataTypes.StringType),
      StructField("pse__Billings__pc",DataTypes.StringType),
      StructField("pse__Bookings__pc",DataTypes.StringType),
      StructField("pse__Credited_Non_Billable_Internal_Hours__pc",DataTypes.StringType),
      StructField("pse__Current_Time_Period_End_Date__pc",DataTypes.StringType),
      StructField("pse__Current_Time_Period__pc",DataTypes.StringType),
      StructField("pse__Daily_Default_Cost_Rate__pc",DataTypes.StringType),
      StructField("pse__Default_Cost_Rate__pc",DataTypes.StringType),
      StructField("pse__Exclude_From_Missing_Timecards__pc",DataTypes.StringType),
      StructField("pse__Exclude_From_Time_Calculations__pc",DataTypes.StringType),
      StructField("pse__Exclude_from_Resource_Planner__pc",DataTypes.StringType),
      StructField("pse__Excluded_Hours__pc",DataTypes.StringType),
      StructField("pse__Expense_Budget__pc",DataTypes.StringType),
      StructField("pse__Expense_Costs__pc",DataTypes.StringType),
      StructField("pse__External_Costs__pc",DataTypes.StringType),
      StructField("pse__External_Resource__pc",DataTypes.StringType),
      StructField("pse__Group__pc",DataTypes.StringType),
      StructField("pse__Hist_Sch_Utilization_Billable_Hours__pc",DataTypes.StringType),
      StructField("pse__Hist_Sch_Utilization_Credited_Hours__pc",DataTypes.StringType),
      StructField("pse__Hist_Sch_Utilization_Excluded_Hours__pc",DataTypes.StringType),
      StructField("pse__Hist_Sch_Utilization_Held_Hours__pc",DataTypes.StringType),
      StructField("pse__Hist_Sch_Utilization_Non_Billable_Hrs__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization_Billable_Hours__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization_Calendar_Hours__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization_Credited_Hours__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization_Excluded_Hours__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization_Non_Billable_Hrs__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization_Target_Attainment__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization_Target_Hours__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization_Target__pc",DataTypes.StringType),
      StructField("pse__Historical_Utilization__pc",DataTypes.StringType),
      StructField("pse__Internal_Budget__pc",DataTypes.StringType),
      StructField("pse__Internal_Costs__pc",DataTypes.StringType),
      StructField("pse__Invoiced__pc",DataTypes.StringType),
      StructField("pse__Is_Resource_Active__pc",DataTypes.StringType),
      StructField("pse__Is_Resource__pc",DataTypes.StringType),
      StructField("pse__Languages__pc",DataTypes.StringType),
      StructField("pse__Last_Date__pc",DataTypes.StringType),
      StructField("pse__Latitude_PSA__pc",DataTypes.StringType),
      StructField("pse__Level__pc",DataTypes.StringType),
      StructField("pse__Longitude_PSA__pc",DataTypes.StringType),
      StructField("pse__Margin__pc",DataTypes.StringType),
      StructField("pse__Non_Billable_External_Hours__pc",DataTypes.StringType),
      StructField("pse__Non_Billable_Internal_Hours__pc",DataTypes.StringType),
      StructField("pse__Other_Costs__pc",DataTypes.StringType),
      StructField("pse__Pass_Through_Billings__pc",DataTypes.StringType),
      StructField("pse__Practice__pc",DataTypes.StringType),
      StructField("pse__Pre_Billed__pc",DataTypes.StringType),
      StructField("pse__Region__pc",DataTypes.StringType),
      StructField("pse__Resource_Role__pc",DataTypes.StringType),
      StructField("pse__Revenue__pc",DataTypes.StringType),
      StructField("pse__Salesforce_User__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Billable_Hours__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Calendar_Hours__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Credited_Hours__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Excluded_Hours__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Held_Hours__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Non_Billable_Hrs__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Target_Attainment__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Target_Hours__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization_Target__pc",DataTypes.StringType),
      StructField("pse__Scheduled_Utilization__pc",DataTypes.StringType),
      StructField("pse__Start_Date__pc",DataTypes.StringType),
      StructField("pse__Total_Costs__pc",DataTypes.StringType),
      StructField("pse__Total_Time_Period_Hours__pc",DataTypes.StringType),
      StructField("pse__Total_Utilization__pc",DataTypes.StringType),
      StructField("pse__Utilization_Calculation_Date__pc",DataTypes.StringType),
      StructField("pse__Utilization_Elapsed_Hours__pc",DataTypes.StringType),
      StructField("pse__Utilization_Full_Time_Period__pc",DataTypes.StringType),
      StructField("pse__Utilization_Last_Update_Date__pc",DataTypes.StringType),
      StructField("pse__Utilization_Last_Updated_By__pc",DataTypes.StringType),
      StructField("pse__Utilization_Target_Attainment__pc",DataTypes.StringType),
      StructField("pse__Utilization_Target_Average__pc",DataTypes.StringType),
      StructField("pse__Utilization_Target_Hours__pc",DataTypes.StringType),
      StructField("pse__Utilization_Target__pc",DataTypes.StringType),
      StructField("pse__Utilization__pc",DataTypes.StringType),
      StructField("pse__Work_Calendar__pc",DataTypes.StringType),
      StructField("psa_report__Hist_Sch_Utilization__pc",DataTypes.StringType),
      StructField("psa_report__Resource_Name__pc",DataTypes.StringType),
      StructField("CKSW__AddressKey__pc",DataTypes.StringType),
      StructField("CKSW__District__pc",DataTypes.StringType),
      StructField("CKSW__Key__pc",DataTypes.StringType),
      StructField("CKSW__Region__pc",DataTypes.StringType),
      StructField("Address_Line1__pc",DataTypes.StringType),
      StructField("Address_Line2__pc",DataTypes.StringType),
      StructField("Address_Line3__pc",DataTypes.StringType),
      StructField("City_Area_Name__pc",DataTypes.StringType),
      StructField("Description__pc",DataTypes.StringType),
      StructField("Organization_Name__pc",DataTypes.StringType),
      StructField("Postal_Extension_Code__pc",DataTypes.StringType),
      StructField("Preferred_Language_Code__pc",DataTypes.StringType),
      StructField("Service_Sales_Contact__pc",DataTypes.StringType),
      StructField("User_Profile__pc",DataTypes.StringType),
      StructField("Alternate_Preferred_Customer_Language__pc",DataTypes.StringType),
      StructField("Case_Closure_Notification_Opt_In__pc",DataTypes.StringType),
      StructField("Case_Creation_Notification_Opt_In__pc",DataTypes.StringType),
      StructField("Email_Quality_Survey_Opt_In__pc",DataTypes.StringType),
      StructField("GSD_Manager_Email__pc",DataTypes.StringType),
      StructField("GSD_Manager__pc",DataTypes.StringType),
      StructField("Part_Delivered_Notification_Opt_In__pc",DataTypes.StringType),
      StructField("Phone_Quality_Survey_Opt_In__pc",DataTypes.StringType),
      StructField("Preferred_Language__pc",DataTypes.StringType),
      StructField("Service_Delivery_Email_Opt_In__pc",DataTypes.StringType),
      StructField("Service_Delivery_Fax_Opt_In__pc",DataTypes.StringType),
      StructField("Service_Delivery_Mail_Opt_In__pc",DataTypes.StringType),
      StructField("Service_Delivery_Mobile_Opt_In__pc",DataTypes.StringType),
      StructField("Service_Delivery_Page_Opt_In__pc",DataTypes.StringType),
      StructField("Service_Delivery_Phone_Opt_In__pc",DataTypes.StringType),
      StructField("Service_Delivery_SMS_Opt_In__pc",DataTypes.StringType),
      StructField("Telephone_Access_Code__pc",DataTypes.StringType),
      StructField("Separation_Contact__pc",DataTypes.StringType),
      StructField("Country_Code__pc",DataTypes.StringType),
      StructField("pse__ERP_Worker_Correlation_Id__pc",DataTypes.StringType),
      StructField("pse__Exclude_From_Time_Variance__pc",DataTypes.StringType),
      StructField("Last_Login__pc",DataTypes.StringType),
      StructField("Phone_Number_Numeric__pc",DataTypes.StringType),
      StructField("et4ae5__HasOptedOutOfMobile__pc",DataTypes.StringType),
      StructField("et4ae5__Mobile_Country_Code__pc",DataTypes.StringType),
      StructField("MDM_ContactSync_Status__pc",DataTypes.StringType),
      StructField("MDM_Person_ID__pc",DataTypes.StringType),
      StructField("ringdna100__Call_Attempts__pc",DataTypes.StringType),
      StructField("ringdna100__Days_Since_Last_Attempt__pc",DataTypes.StringType),
      StructField("ringdna100__Email_Attempts__pc",DataTypes.StringType),
      StructField("ringdna100__First_Inbound_Call__pc",DataTypes.StringType),
      StructField("ringdna100__First_Outbound_Call__pc",DataTypes.StringType),
      StructField("ringdna100__Last_Email_Attempt__pc",DataTypes.StringType),
      StructField("ringdna100__Last_Inbound_Call__pc",DataTypes.StringType),
      StructField("ringdna100__Last_Outbound_Call__pc",DataTypes.StringType),
      StructField("ringdna100__Response_Type__pc",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Call_Attempt_Days__pc",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Call_Attempt_Minutes__pc",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Email_Attempt_Days__pc",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Email_Attempt_Minutes__pc",DataTypes.StringType),
      StructField("ringdna100__Time_to_First_Dial_Minutes__pc",DataTypes.StringType),
      StructField("ringdna100__Time_to_First_Response__pc",DataTypes.StringType),
      StructField("Tenant_Id__pc",DataTypes.StringType),
      StructField("VisitOps__DietType__pc",DataTypes.StringType),
      StructField("VisitOps__DietaryRequirements__pc",DataTypes.StringType),
      StructField("VisitOps__LinkedInUrl__pc",DataTypes.StringType),
      StructField("VisitOps__Role__pc",DataTypes.StringType),
      StructField("pse__API_Resource_Correlation_Id__pc",DataTypes.StringType),
      StructField("Location_ID__pc",DataTypes.StringType),
      StructField("pse__Employment_Status_Effective_Date__pc",DataTypes.StringType),
      StructField("pse__Employment_Status__pc",DataTypes.StringType),
      StructField("Shipping_City__pc",DataTypes.StringType),
      StructField("LID__LinkedIn_Company_Id__pc",DataTypes.StringType),
      StructField("LID__LinkedIn_Member_Token__pc",DataTypes.StringType),
      StructField("Block_Usage__pc",DataTypes.StringType),
      StructField("ringdna100__First_Inbound_Message__pc",DataTypes.StringType),
      StructField("IsActive__pc",DataTypes.StringType),
      StructField("IsConvertedFromLead__pc",DataTypes.StringType),
      StructField("Isolation_Comment__pc",DataTypes.StringType),
      StructField("Isolation_Reason__pc",DataTypes.StringType),
      StructField("MDCP_Last_Sync_Date__pc",DataTypes.StringType),
      StructField("Phonetic_Second_Name__pc",DataTypes.StringType),
      StructField("Privacy_Loaded__pc",DataTypes.StringType),
      StructField("Profile_Name__pc",DataTypes.StringType),
      StructField("SFDC_MDCP_Batch_Sync_Flag__pc",DataTypes.StringType),
      StructField("Second_Name_Local__pc",DataTypes.StringType),
      StructField("Second_Name__pc",DataTypes.StringType),
      StructField("ringdna100__First_Outbound_Message__pc",DataTypes.StringType),
      StructField("Previous_MDCP_Contact_Relationship__pc",DataTypes.StringType),
      StructField("Teleoptin_Required__pc",DataTypes.StringType),
      StructField("GDPR_Governed__pc",DataTypes.StringType),
      StructField("ringdna100__Last_Inbound_Message__pc",DataTypes.StringType),
      StructField("ringdna100__Last_Outbound_Message__pc",DataTypes.StringType),
      StructField("ringdna100__Message_Attempts__pc",DataTypes.StringType),
      StructField("ringdna100__RingDNA_Context__pc",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Message_Attempt_Days__pc",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Message_Attempt_Minutes__pc",DataTypes.StringType)
    )
  )

  val opportunityschema = StructType(
    List(
      StructField("Id",DataTypes.StringType),
      StructField("IsDeleted",DataTypes.StringType),
      StructField("AccountId",DataTypes.StringType),
      StructField("RecordTypeId",DataTypes.StringType),
      StructField("IsPrivate",DataTypes.StringType),
      StructField("Name",DataTypes.StringType),
      StructField("Description",DataTypes.StringType),
      StructField("StageName",DataTypes.StringType),
      StructField("Amount",DataTypes.StringType),
      StructField("Probability",DataTypes.StringType),
      StructField("ExpectedRevenue",DataTypes.StringType),
      StructField("TotalOpportunityQuantity",DataTypes.StringType),
      StructField("CloseDate",DataTypes.StringType),
      StructField("Type",DataTypes.StringType),
      StructField("NextStep",DataTypes.StringType),
      StructField("LeadSource",DataTypes.StringType),
      StructField("IsClosed",DataTypes.StringType),
      StructField("IsWon",DataTypes.StringType),
      StructField("ForecastCategory",DataTypes.StringType),
      StructField("ForecastCategoryName",DataTypes.StringType),
      StructField("CurrencyIsoCode",DataTypes.StringType),
      StructField("CampaignId",DataTypes.StringType),
      StructField("HasOpportunityLineItem",DataTypes.StringType),
      StructField("Pricebook2Id",DataTypes.StringType),
      StructField("OwnerId",DataTypes.StringType),
      StructField("CreatedDate",DataTypes.StringType),
      StructField("CreatedById",DataTypes.StringType),
      StructField("LastModifiedDate",DataTypes.StringType),
      StructField("LastModifiedById",DataTypes.StringType),
      StructField("SystemModstamp",DataTypes.StringType),
      StructField("LastActivityDate",DataTypes.StringType),
      StructField("FiscalQuarter",DataTypes.StringType),
      StructField("FiscalYear",DataTypes.StringType),
      StructField("Fiscal",DataTypes.StringType),
      StructField("LastViewedDate",DataTypes.StringType),
      StructField("LastReferencedDate",DataTypes.StringType),
      StructField("PartnerAccountId",DataTypes.StringType),
      StructField("SyncedQuoteId",DataTypes.StringType),
      StructField("ContractId",DataTypes.StringType),
      StructField("HasOpenActivity",DataTypes.StringType),
      StructField("HasOverdueTask",DataTypes.StringType),
      StructField("Business_Group2__c",DataTypes.StringType),
      StructField("Country__c",DataTypes.StringType),
      StructField("Customer_Budget_Amount__c",DataTypes.StringType),
      StructField("Deal_Checklist__c",DataTypes.StringType),
      StructField("Fulfillment__c",DataTypes.StringType),
      StructField("HPFS_Needed__c",DataTypes.StringType),
      StructField("HP_Financing_Indicator_Code__c",DataTypes.StringType),
      StructField("HP_Solution__c",DataTypes.StringType),
      StructField("Has_Campaign__c",DataTypes.StringType),
      StructField("Is_Opportunity__c",DataTypes.StringType),
      StructField("Legacy_ref_Id__c",DataTypes.StringType),
      StructField("Opportunity_ID__c",DataTypes.StringType),
      StructField("Opportunity_Total_Amount__c",DataTypes.StringType),
      StructField("Opportunity_Update__c",DataTypes.StringType),
      StructField("Owner__c",DataTypes.StringType),
      StructField("Owner_s_Global_Business_Unit__c",DataTypes.StringType),
      StructField("Related_Opportunity__c",DataTypes.StringType),
      StructField("Route_To_Market__c",DataTypes.StringType),
      StructField("Source_System_Lead_ID__c",DataTypes.StringType),
      StructField("Stage_1_2_Values__c",DataTypes.StringType),
      StructField("Term_Credit_Line__c",DataTypes.StringType),
      StructField("Term_Credit_Request_Status__c",DataTypes.StringType),
      StructField("Total_Contract_Length_In_Months__c",DataTypes.StringType),
      StructField("Win_Loss_Reason__c",DataTypes.StringType),
      StructField("Within_Rolling_12_Months__c",DataTypes.StringType),
      StructField("Within_Rolling_6_Months__c",DataTypes.StringType),
      StructField("has_Multi_BG_Products__c",DataTypes.StringType),
      StructField("Alliance_Channel_Partner_Count__c",DataTypes.StringType),
      StructField("Competitors_Added__c",DataTypes.StringType),
      StructField("Account_Shipping_Country__c",DataTypes.StringType),
      StructField("Account_Shipping_PostalCode__c",DataTypes.StringType),
      StructField("Account_Shipping_State__c",DataTypes.StringType),
      StructField("Account_Shipping_Street__c",DataTypes.StringType),
      StructField("Assigned_to_partner_date__c",DataTypes.StringType),
      StructField("Close_Date_Delta__c",DataTypes.StringType),
      StructField("Close_Date_Push_Counter__c",DataTypes.StringType),
      StructField("Converted_From_Lead__c",DataTypes.StringType),
      StructField("Converted_by_Partner__c",DataTypes.StringType),
      StructField("Current_User_BG__c",DataTypes.StringType),
      StructField("Days_Since_Partner_Last_Modified__c",DataTypes.StringType),
      StructField("GRM_ID__c",DataTypes.StringType),
      StructField("Incumbent_Competitor__c",DataTypes.StringType),
      StructField("GSD_Lead_Name__c",DataTypes.StringType),
      StructField("Last_Modified_by_Partner__c",DataTypes.StringType),
      StructField("Lead_Created_Date__c",DataTypes.StringType),
      StructField("List_Code__c",DataTypes.StringType),
      StructField("List_Id__c",DataTypes.StringType),
      StructField("Managed_By__c",DataTypes.StringType),
      StructField("OpportunityGroup__c",DataTypes.StringType),
      StructField("Opportunity_Sales_Stage__c",DataTypes.StringType),
      StructField("Partner_acknowledged__c",DataTypes.StringType),
      StructField("Primary_Competitor__c",DataTypes.StringType),
      StructField("Primary_Partner__c",DataTypes.StringType),
      StructField("Prior_Sales_Stage__c",DataTypes.StringType),
      StructField("Qualification_Team_ID__c",DataTypes.StringType),
      StructField("Qualification_Team_Name__c",DataTypes.StringType),
      StructField("Renewal_Sub_Type__c",DataTypes.StringType),
      StructField("Renewal_Type__c",DataTypes.StringType),
      StructField("SAP_Feed__c",DataTypes.StringType),
      StructField("Strategic_Initiative__c",DataTypes.StringType),
      StructField("Tactic_Code__c",DataTypes.StringType),
      StructField("Tactic_Name__c",DataTypes.StringType),
      StructField("Total_Margin_Percentage__c",DataTypes.StringType),
      StructField("Won_Lost_Date__c",DataTypes.StringType),
      StructField("Min_Book_Ship_Date__c",DataTypes.StringType),
      StructField("Product_Last_Modified__c",DataTypes.StringType),
      StructField("Total_First_12_Month_Value__c",DataTypes.StringType),
      StructField("Total_First_Fiscal_Yr_Value__c",DataTypes.StringType),
      StructField("Total_Margin_Amount__c",DataTypes.StringType),
      StructField("List_Name__c",DataTypes.StringType),
      StructField("Primary_Campaign_Name__c",DataTypes.StringType),
      StructField("Tactic_ID__c",DataTypes.StringType),
      StructField("Velocity__c",DataTypes.StringType),
      StructField("Account_Billing_Country__c",DataTypes.StringType),
      StructField("Account_Private_Opportunity__c",DataTypes.StringType),
      StructField("Account_Shipping_City__c",DataTypes.StringType),
      StructField("Action_1__c",DataTypes.StringType),
      StructField("Action_2__c",DataTypes.StringType),
      StructField("Activity_Plan__c",DataTypes.StringType),
      StructField("Confidential__c",DataTypes.StringType),
      StructField("Current_Stage_days__c",DataTypes.StringType),
      StructField("Deal_Action_Plan_Type__c",DataTypes.StringType),
      StructField("Deal_Expiration_Date__c",DataTypes.StringType),
      StructField("Deal_Id__c",DataTypes.StringType),
      StructField("Deal_Registration_Status__c",DataTypes.StringType),
      StructField("Deal_Submission_Date__c",DataTypes.StringType),
      StructField("DynamicUrl__c",DataTypes.StringType),
      StructField("Error_Stage_Amount__c",DataTypes.StringType),
      StructField("Finance_Type__c",DataTypes.StringType),
      StructField("HP_Not_Pursued_Stage_Amount__c",DataTypes.StringType),
      StructField("HP_Not_Pursued_Stage_Count__c",DataTypes.StringType),
      StructField("IsOwnerAssigned__c",DataTypes.StringType),
      StructField("Last_Stage_Change_Date__c",DataTypes.StringType),
      StructField("Lease_Type__c",DataTypes.StringType),
      StructField("Lost_Or_HP_Not_Pursed_Not_123_Amount__c",DataTypes.StringType),
      StructField("Lost_Or_HP_Not_Pursed_Not_123_Count__c",DataTypes.StringType),
      StructField("Lost_Stage_Amount__c",DataTypes.StringType),
      StructField("Lost_Stage_Count__c",DataTypes.StringType),
      StructField("Opportunity_Detail__c",DataTypes.StringType),
      StructField("Opportunity_Outside_Owner_s_Terr__c",DataTypes.StringType),
      StructField("Placeholder_Status_1__c",DataTypes.StringType),
      StructField("Premier_Type__c",DataTypes.StringType),
      StructField("Previous_Sales_Stage__c",DataTypes.StringType),
      StructField("Quote_Status_Update_Notification__c",DataTypes.StringType),
      StructField("Record_Type_Name__c",DataTypes.StringType),
      StructField("SW_ELA__c",DataTypes.StringType),
      StructField("SW_Premier__c",DataTypes.StringType),
      StructField("SW_Push_To__c",DataTypes.StringType),
      StructField("SW_RTS__c",DataTypes.StringType),
      StructField("SW_Uplift__c",DataTypes.StringType),
      StructField("SW_Upsell__c",DataTypes.StringType),
      StructField("SW_Win_Back__c",DataTypes.StringType),
      StructField("Sales_Stage2__c",DataTypes.StringType),
      StructField("SendEmailNotification__c",DataTypes.StringType),
      StructField("Sub_Type__c",DataTypes.StringType),
      StructField("Submitted_Date__c",DataTypes.StringType),
      StructField("TS_Multi_BG__c",DataTypes.StringType),
      StructField("TS_Multinational__c",DataTypes.StringType),
      StructField("TS_PROP__c",DataTypes.StringType),
      StructField("Value__c",DataTypes.StringType),
      StructField("X06_Stage_Amount__c",DataTypes.StringType),
      StructField("X06_Stage_Count__c",DataTypes.StringType),
      StructField("account_blacklist__c",DataTypes.StringType),
      StructField("isResubmitted__c",DataTypes.StringType),
      StructField("CountOfOppLineItem__c",DataTypes.StringType),
      StructField("CountOfQuoteSyncOppLineItem__c",DataTypes.StringType),
      StructField("HasProductLineSum__c",DataTypes.StringType),
      StructField("HasQuoteSyncProductLineSum__c",DataTypes.StringType),
      StructField("HasQuoteSyncSubProductLineSum__c",DataTypes.StringType),
      StructField("HasSubProductLineSum__c",DataTypes.StringType),
      StructField("Quote_Sync_Count__c",DataTypes.StringType),
      StructField("Case_Safe_ID__c",DataTypes.StringType),
      StructField("Customer_Engagement__c",DataTypes.StringType),
      StructField("Term_Credit_Line3__c",DataTypes.StringType),
      StructField("DMAPP__Dealmaker_Opportunity__c",DataTypes.StringType),
      StructField("BigMachines__Line_Items__c",DataTypes.StringType),
      StructField("Account_Region__c",DataTypes.StringType),
      StructField("Estimated_Multi_Country_Value__c",DataTypes.StringType),
      StructField("MultiGBU__c",DataTypes.StringType),
      StructField("Multi_Country_Type__c",DataTypes.StringType),
      StructField("No_Alliance_Partner__c",DataTypes.StringType),
      StructField("No_Competitor__c",DataTypes.StringType),
      StructField("Non_standard_Opportunity__c",DataTypes.StringType),
      StructField("Non_standard_t_c_s__c",DataTypes.StringType),
      StructField("Alliance_Partners_Count__c",DataTypes.StringType),
      StructField("ParticipatingRegionAMS__c",DataTypes.StringType),
      StructField("HP_Opportunity_Updated_Date__c",DataTypes.StringType),
      StructField("ParticipatingRegionEMEA__c",DataTypes.StringType),
      StructField("Big_Deal_Review__c",DataTypes.StringType),
      StructField("Deal_Source__c",DataTypes.StringType),
      StructField("Original_Slipped_Quarter__c",DataTypes.StringType),
      StructField("Slipped_Deal_Counter__c",DataTypes.StringType),
      StructField("Revenue_Recognition_Date__c",DataTypes.StringType),
      StructField("At_Risk__c",DataTypes.StringType),
      StructField("Difference_in_Maintenance__c",DataTypes.StringType),
      StructField("Down_Select__c",DataTypes.StringType),
      StructField("Economic_Value__c",DataTypes.StringType),
      StructField("Has_Close_Plan__c",DataTypes.StringType),
      StructField("Lead_Creator__c",DataTypes.StringType),
      StructField("Lead_ID__c",DataTypes.StringType),
      StructField("Lead_Qualifier__c",DataTypes.StringType),
      StructField("Multi_Year_Decline_Reason__c",DataTypes.StringType),
      StructField("Price2Win__c",DataTypes.StringType),
      StructField("Proposal_Due_Date__c",DataTypes.StringType),
      StructField("RFI_Date__c",DataTypes.StringType),
      StructField("RFP_Date__c",DataTypes.StringType),
      StructField("Record_Open_Date__c",DataTypes.StringType),
      StructField("Turn_Days__c",DataTypes.StringType),
      StructField("Close_Plan_Count__c",DataTypes.StringType),
      StructField("Max_Book_Ship_Date__c",DataTypes.StringType),
      StructField("CustomerCancelled__c",DataTypes.StringType),
      StructField("ES_Opportunity_Type__c",DataTypes.StringType),
      StructField("External_Telemarketing_Agency__c",DataTypes.StringType),
      StructField("HIPAA_Compliance_Required__c",DataTypes.StringType),
      StructField("MDCP_Organization_ID__c",DataTypes.StringType),
      StructField("OpportunityOwnerType__c",DataTypes.StringType),
      StructField("Parent_Finance_Type__c",DataTypes.StringType),
      StructField("Partner_Company__c",DataTypes.StringType),
      StructField("Pipeline_Exclusion__c",DataTypes.StringType),
      StructField("Distributor_Count__c",DataTypes.StringType),
      StructField("owner_email__c",DataTypes.StringType),
      StructField("Services360_Account__c",DataTypes.StringType),
      StructField("Allow_DistiSwitch__c",DataTypes.StringType),
      StructField("Benefit__c",DataTypes.StringType),
      StructField("End_Customer_Name__c",DataTypes.StringType),
      StructField("Expiration_Date__c",DataTypes.StringType),
      StructField("Is_Quote_Updated_Sales_Stage__c",DataTypes.StringType),
      StructField("Lost_Not_Pursued_Reason__c",DataTypes.StringType),
      StructField("ModifiedByPartner__c",DataTypes.StringType),
      StructField("OpportunityName__c",DataTypes.StringType),
      StructField("Record_Type_Name1__c",DataTypes.StringType),
      StructField("ResellerName__c",DataTypes.StringType),
      StructField("Reseller_Name__c",DataTypes.StringType),
      StructField("Services_360_Pro_Won_Loss_Reason__c",DataTypes.StringType),
      StructField("Status__c",DataTypes.StringType),
      StructField("Your_Comments__c",DataTypes.StringType),
      StructField("Approval_TAT2__c",DataTypes.StringType),
      StructField("Next_Switching_Date__c",DataTypes.StringType),
      StructField("SupportRequest__c",DataTypes.StringType),
      StructField("Switching_Letter__c",DataTypes.StringType),
      StructField("CountOfAcceptedQuote__c",DataTypes.StringType),
      StructField("Contact__c",DataTypes.StringType),
      StructField("Driving_Opportunity__c",DataTypes.StringType),
      StructField("General_Email_Box1__c",DataTypes.StringType),
      StructField("General_Email_Box2__c",DataTypes.StringType),
      StructField("General_Email_Box3__c",DataTypes.StringType),
      StructField("Has_Opportunity_Plan__c",DataTypes.StringType),
      StructField("Has_Won_Lost_Analysis__c",DataTypes.StringType),
      StructField("IsDOB__c",DataTypes.StringType),
      StructField("pse__Group__c",DataTypes.StringType),
      StructField("Opportunity_Group__c",DataTypes.StringType),
      StructField("OwnerRoleType__c",DataTypes.StringType),
      StructField("Owner_Company_Type__c",DataTypes.StringType),
      StructField("Projected_Group_Value__c",DataTypes.StringType),
      StructField("Send_Switching_Notification__c",DataTypes.StringType),
      StructField("Total_Group_Value__c",DataTypes.StringType),
      StructField("Winning_Bid__c",DataTypes.StringType),
      StructField("Winning_Competitor__c",DataTypes.StringType),
      StructField("Opportunity_Group_Type__c",DataTypes.StringType),
      StructField("ManualPipelineExclusion__c",DataTypes.StringType),
      StructField("Initial_Close_Date__c",DataTypes.StringType),
      StructField("Close_Date_pushed_more_than_2_months__c",DataTypes.StringType),
      StructField("pse__IsParentOpportunityServices__c",DataTypes.StringType),
      StructField("pse__Is_Change_Request__c",DataTypes.StringType),
      StructField("pse__Is_Services_Opportunity__c",DataTypes.StringType),
      StructField("pse__Parent_Opportunity__c",DataTypes.StringType),
      StructField("pse__Practice__c",DataTypes.StringType),
      StructField("pse__PreBilledAmount__c",DataTypes.StringType),
      StructField("pse__Pre_Billed_Amount__c",DataTypes.StringType),
      StructField("pse__Primary_Project__c",DataTypes.StringType),
      StructField("pse__Region__c",DataTypes.StringType),
      StructField("pse__Services_Attached_Percent_From_Products__c",DataTypes.StringType),
      StructField("pse__Services_Attached_From_Products__c",DataTypes.StringType),
      StructField("Customer_Contact_First_Name__c",DataTypes.StringType),
      StructField("Customer_Contact_Last_Name__c",DataTypes.StringType),
      StructField("Customer_Email_Address__c",DataTypes.StringType),
      StructField("Customer_Telephone_Number__c",DataTypes.StringType),
      StructField("Days_for_Lead_Conversion_by_the_SalesRep__c",DataTypes.StringType),
      StructField("Deal_Classification__c",DataTypes.StringType),
      StructField("Forecast_Category__c",DataTypes.StringType),
      StructField("GSD_Date_Crossed_SS_4A__c",DataTypes.StringType),
      StructField("GSD_Days_to_Conversion__c",DataTypes.StringType),
      StructField("GSD_Days_to_cross_SS_4A__c",DataTypes.StringType),
      StructField("GSD_Referred_by_Country__c",DataTypes.StringType),
      StructField("GSD_Referred_by_Email_address__c",DataTypes.StringType),
      StructField("GSD_Referred_by_Full_Name__c",DataTypes.StringType),
      StructField("GSD_Velocity_from_Lead__c",DataTypes.StringType),
      StructField("Hour__c",DataTypes.StringType),
      StructField("Last_Updated_Date_by_SourceSystem__c",DataTypes.StringType),
      StructField("Order_Exists__c",DataTypes.StringType),
      StructField("Ordering_Contact__c",DataTypes.StringType),
      StructField("PPOFlag__c",DataTypes.StringType),
      StructField("Primary_Pipeline_Owner__c",DataTypes.StringType),
      StructField("Skip_Validation__c",DataTypes.StringType),
      StructField("Updated_By_SourceSystem__c",DataTypes.StringType),
      StructField("Account_confidential_flag__c",DataTypes.StringType),
      StructField("Days_since_last_modified__c",DataTypes.StringType),
      StructField("Days_to_win_or_lost_from_Stage_4a__c",DataTypes.StringType),
      StructField("Error_Code__c",DataTypes.StringType),
      StructField("GSD_Case_ID__c",DataTypes.StringType),
      StructField("GSD_Project_ID__c",DataTypes.StringType),
      StructField("GSD_Sub_Task_ID__c",DataTypes.StringType),
      StructField("HP_Lead_ID__c",DataTypes.StringType),
      StructField("Reseller_Company__c",DataTypes.StringType),
      StructField("Campaign__c",DataTypes.StringType),
      StructField("RMR_Facility__c",DataTypes.StringType),
      StructField("RMR_Org_ID__c",DataTypes.StringType),
      StructField("RMR_Primary_Operational_Role__c",DataTypes.StringType),
      StructField("RMR_Secondary_Operational_Role__c",DataTypes.StringType),
      StructField("GSD_Referred_By__c",DataTypes.StringType),
      StructField("Initial_Opportunity_Value__c",DataTypes.StringType),
      StructField("Moved_to_HPI__c",DataTypes.StringType),
      StructField("Tier_1_Opportunity_Value__c",DataTypes.StringType),
      StructField("Account_Oppty_Id__c",DataTypes.StringType),
      StructField("Last_Modified_Full_Name__c",DataTypes.StringType),
      StructField("pse__Rate_Card_Discount_Limit__c",DataTypes.StringType),
      StructField("pse__Rate_Card_Percentage_Discount__c",DataTypes.StringType),
      StructField("pse__Rate_Card_Set__c",DataTypes.StringType),
      StructField("DM_Status__c",DataTypes.StringType),
      StructField("End_Customer_Text__c",DataTypes.StringType),
      StructField("Opportunity_Owner__c",DataTypes.StringType),
      StructField("Reconciled__c",DataTypes.StringType),
      StructField("Opportunity_Name__c",DataTypes.StringType),
      StructField("Expected_Service_Delivery_Start_Date__c",DataTypes.StringType),
      StructField("Partner_Selected_Site__c",DataTypes.StringType),
      StructField("Cloned_From_Partner_Opportunity__c",DataTypes.StringType),
      StructField("Disable_Quote_Sync__c",DataTypes.StringType),
      StructField("Engagement_Type__c",DataTypes.StringType),
      StructField("Financial_Services_Update__c",DataTypes.StringType),
      StructField("Source_Opportunity__c",DataTypes.StringType),
      StructField("Total_Value_to_HPE_Aruba__c",DataTypes.StringType),
      StructField("Are_you_the_Sales_Contact_for_this_deal__c",DataTypes.StringType),
      StructField("ArubaTitle__c",DataTypes.StringType),
      StructField("Aruba_Role__c",DataTypes.StringType),
      StructField("COmpetitors_List__c",DataTypes.StringType),
      StructField("Channel_Rep__c",DataTypes.StringType),
      StructField("Deal_Expiration__c",DataTypes.StringType),
      StructField("Disti_Read_Access__c",DataTypes.StringType),
      StructField("For_Aruba__c",DataTypes.StringType),
      StructField("Number_of_users__c",DataTypes.StringType),
      StructField("Partner_Contribution_Role__c",DataTypes.StringType),
      StructField("Partner_Deal_Reference_Number__c",DataTypes.StringType),
      StructField("Primary_sales_contact__c",DataTypes.StringType),
      StructField("Sales_Rep__c",DataTypes.StringType),
      StructField("Aruba_Original_DR_Product_IDs__c",DataTypes.StringType),
      StructField("Aruba_Original_DR_Products__c",DataTypes.StringType),
      StructField("Tenant_Id__c",DataTypes.StringType),
      StructField("HPE_Aruba_Wired__c",DataTypes.StringType),
      StructField("HPE_Aruba__c",DataTypes.StringType),
      StructField("Govt_LLC__c",DataTypes.StringType),
      StructField("Primary_Pipeline_Owner_User__c",DataTypes.StringType),
      StructField("Primary_Distributor__c",DataTypes.StringType),
      StructField("Primary_Pipeline_Owner_User_Email__c",DataTypes.StringType),
      StructField("Primary_Pipeline_Owner_User_Manager__c",DataTypes.StringType),
      StructField("Primary_Pipeline_Owner_User_Role__c",DataTypes.StringType),
      StructField("Risk_Category__c",DataTypes.StringType),
      StructField("CV_Acct_Type__c",DataTypes.StringType),
      StructField("CV_Payment_Type__c",DataTypes.StringType),
      StructField("Number_of_Opptys__c",DataTypes.StringType),
      StructField("Opportunity_Source__c",DataTypes.StringType),
      StructField("VisitOps__MainCompetitors__c",DataTypes.StringType),
      StructField("VisitOps__TrackingNumber__c",DataTypes.StringType),
      StructField("VisitOps__Visit_Count__c",DataTypes.StringType),
      StructField("Cloud_Platform_Count__c",DataTypes.StringType),
      StructField("NO_ProductLineCount__c",DataTypes.StringType),
      StructField("DS_Denali__DS_Owner_ID__c",DataTypes.StringType),
      StructField("DS_Denali__Datetime_of_Last_Disposition_DS__c",DataTypes.StringType),
      StructField("DS_Denali__Last_Call_Campaign_Name__c",DataTypes.StringType),
      StructField("DS_Denali__Last_Disposition_DS__c",DataTypes.StringType),
      StructField("DS_Denali__Next_Call_DS__c",DataTypes.StringType),
      StructField("DS_Denali__Total_Call_Count_DS__c",DataTypes.StringType),
      StructField("Primary_Distributor_MDCP_Org_Id__c",DataTypes.StringType),
      StructField("pse__Forecast_Curve__c",DataTypes.StringType),
      StructField("eRate_oppty__c",DataTypes.StringType),
      StructField("Deal_Band_Size__c",DataTypes.StringType),
      StructField("LID__Is_Influenced__c",DataTypes.StringType),
      StructField("LID__LinkedIn_Company_Id__c",DataTypes.StringType),
      StructField("Previous_Owner__c",DataTypes.StringType),
      StructField("Altify_Sales_Process__c",DataTypes.StringType),
      StructField("Bypass_Validation__c",DataTypes.StringType),
      StructField("Opportunity_Assigning_User__c",DataTypes.StringType),
      StructField("Primary_Reseller_Location__c",DataTypes.StringType),
      StructField("Primary_Distributor_Location__c",DataTypes.StringType),
      StructField("SS3_Qualification_Date__c",DataTypes.StringType),
      StructField("SS3_Qualified_Pipeline__c",DataTypes.StringType),
      StructField("SDR_Payee__c",DataTypes.StringType),
      StructField("Partner_Id_for_SR__c",DataTypes.StringType),
      StructField("Partner_Name_for_SR__c",DataTypes.StringType),
      StructField("Max_Book_Ship_Fiscal_Year__c",DataTypes.StringType),
      StructField("Max_Book_Ship_Fiscal_Quarter__c",DataTypes.StringType),
      StructField("ffr__BatchProcess__c",DataTypes.StringType),
      StructField("ringdna100__Call_Attempts__c",DataTypes.StringType),
      StructField("ringdna100__Days_Since_Last_Attempt_Call_or_Email__c",DataTypes.StringType),
      StructField("ringdna100__Email_Attempts__c",DataTypes.StringType),
      StructField("ringdna100__First_Inbound_Call__c",DataTypes.StringType),
      StructField("ringdna100__First_Outbound_Call__c",DataTypes.StringType),
      StructField("ringdna100__Last_Email_Attempt__c",DataTypes.StringType),
      StructField("ringdna100__Last_Inbound_Call__c",DataTypes.StringType),
      StructField("ringdna100__Last_Outbound_Call__c",DataTypes.StringType),
      StructField("ringdna100__Response_Type__c",DataTypes.StringType),
      StructField("ringdna100__RingDNA_Context__c",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Call_Attempt_Days__c",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Call_Attempt_Minutes__c",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Email_Attempt_Days__c",DataTypes.StringType),
      StructField("ringdna100__Time_Since_Last_Email_Attempt_Minutes__c",DataTypes.StringType),
      StructField("ringdna100__Time_to_First_Dial_Minutes__c",DataTypes.StringType),
      StructField("ringdna100__Time_to_First_Response__c",DataTypes.StringType),
      StructField("Qualified_HPEFS_RR__c",DataTypes.StringType),
      StructField("CPCount__c",DataTypes.StringType),
      StructField("Financial_Services_Engaged_Date__c",DataTypes.StringType)
    )
  )
}
